public enum TokenType {
    CLASS, PUBLIC, STATIC, VOID, MAIN, A_PALAVRA_STRING, EXTENDS, 
    ID,
    ABRE_CHAVE, FECHA_CHAVE,
    ABRE_COLCHETE, FECHA_COLCHETE,
    ABRE_PARENTESE, FECHA_PARENTESE,
    PONTO, VIRGULA, PONTO_E_VIRGULA, IGUAL,
    OP_E, OP_OU, OP_MENOR, OP_MAIS, OP_MENOS, OP_VEZES, OP_EXCLAMACAO,
    INT, BOOLEAN,
    NEW, THIS,
    SYSTEM_OUT_PRINTLN,
    WHILE, IF, ELSE, RETURN;
}

